//! The export to TypeScript (Plan.md P6.9, ADR-0015), behind `just gen` and
//! `just gen-check` (the example `typescript`).
//!
//! - [`export`] writes every DTO through ts-rs, one `<Name>.ts` file per
//!   type, into an empty scratch folder. Its config comes from
//!   `Config::new()`, which ignores the `TS_RS_*` environment variables, so
//!   a developer's environment can't change the output. No DTO carries
//!   `#[ts(export)]`, so tests never write files.
//! - [`sync`] makes the committed folder hold exactly that export. It only
//!   ever deletes files ts-rs generated, and refuses to touch a folder that
//!   holds anything else.
//! - [`compare`] lists how the committed folder differs from the export.
//!
//! [`write()`] and [`check()`] combine them, as `just gen` and `just gen-check`
//! do. Each run starts from a fresh, empty scratch folder, and [`export`]
//! refuses one that isn't empty, so a file from an earlier run never reaches
//! the committed folder.

use core::fmt;
use std::collections::BTreeMap;
use std::ffi::OsString;
use std::io;
use std::path::{Path, PathBuf};

use ts_rs::{Config, ExportError, TS};

use crate::error::ErrorResponse;

/// The first line of every file ts-rs 12.0.1 writes. [`sync`] deletes only
/// `.ts` files that start with it.
pub const TS_RS_HEADER: &str = "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.\n";

/// Why the export, the comparison or the sync failed.
#[derive(Debug, thiserror::Error)]
pub enum TypeScriptError {
    /// The scratch folder holds something, which could reach the committed
    /// folder.
    #[error("the scratch folder {} isn't empty", path.display())]
    ScratchNotEmpty {
        /// The scratch folder.
        path: PathBuf,
    },
    /// An entry isn't a file ts-rs generated: a hand-written file, a file
    /// without ts-rs's header, a folder or a link. Nothing was changed.
    #[error(
        "{} isn't a file ts-rs generated, so nothing was changed; the folder may hold only ts-rs's files",
        path.display()
    )]
    Foreign {
        /// The entry.
        path: PathBuf,
    },
    /// ts-rs failed.
    #[error("ts-rs couldn't export the types")]
    Export(#[source] ExportError),
    /// Reading or writing a file or folder failed.
    #[error("couldn't read or write {}", path.display())]
    Io {
        /// The file or folder.
        path: PathBuf,
        /// The OS's error.
        #[source]
        source: io::Error,
    },
}

/// How the committed folder differs from a fresh export, by file name.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Difference {
    /// The export has the file; the folder doesn't.
    Missing(PathBuf),
    /// The folder has the entry; the export doesn't.
    Extra(PathBuf),
    /// Both have it, with different contents.
    Changed(PathBuf),
}

impl Difference {
    /// The file's name.
    #[must_use]
    pub fn file_name(&self) -> &Path {
        match self {
            Self::Missing(name) | Self::Extra(name) | Self::Changed(name) => name,
        }
    }
}

impl fmt::Display for Difference {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Missing(name) => write!(f, "missing: {}", name.display()),
            Self::Extra(name) => write!(f, "not in the export: {}", name.display()),
            Self::Changed(name) => write!(f, "changed: {}", name.display()),
        }
    }
}

/// Exports every DTO into `scratch`, which must exist and be empty.
///
/// # Errors
/// [`TypeScriptError::ScratchNotEmpty`], [`TypeScriptError::Export`] or
/// [`TypeScriptError::Io`].
pub fn export(scratch: &Path) -> Result<(), TypeScriptError> {
    let Some(present) = entries(scratch)? else {
        return Err(TypeScriptError::Io {
            path: scratch.to_path_buf(),
            source: io::ErrorKind::NotFound.into(),
        });
    };
    if !present.is_empty() {
        return Err(TypeScriptError::ScratchNotEmpty {
            path: scratch.to_path_buf(),
        });
    }
    let config = Config::new().with_out_dir(scratch);
    // The root DTOs: `export_all` also writes every type they use. A DTO no
    // listed type uses goes here.
    ErrorResponse::export_all(&config).map_err(TypeScriptError::Export)
}

/// Lists how `dir` differs from the export in `scratch`, by file name. A missing
/// `dir` lacks every file.
///
/// # Errors
/// [`TypeScriptError::Io`].
pub fn compare(scratch: &Path, dir: &Path) -> Result<Vec<Difference>, TypeScriptError> {
    let fresh = entries(scratch)?.unwrap_or_default();
    let committed = entries(dir)?.unwrap_or_default();
    let mut differences: Vec<Difference> = fresh
        .iter()
        .filter_map(|(name, entry)| match committed.get(name) {
            None => Some(Difference::Missing(PathBuf::from(name))),
            Some(other) if other != entry => Some(Difference::Changed(PathBuf::from(name))),
            Some(_) => None,
        })
        .chain(
            committed
                .keys()
                .filter(|name| !fresh.contains_key(*name))
                .map(|name| Difference::Extra(PathBuf::from(name))),
        )
        .collect();
    differences.sort_by(|a, b| a.file_name().cmp(b.file_name()));
    Ok(differences)
}

/// Makes `dir` hold exactly the export in `scratch`: deletes the generated
/// files the export no longer has, and writes the new and changed ones. A
/// missing `dir` is created.
///
/// It first checks every entry in `dir` and in `scratch`: in `dir`, anything
/// but a `.ts` file that starts with [`TS_RS_HEADER`], and in `scratch`,
/// anything but a file, stops it before anything is changed, so a wrong path
/// can never wipe a folder or leave it half synced.
///
/// # Errors
/// [`TypeScriptError::Foreign`] for the first such entry, by name, or
/// [`TypeScriptError::Io`].
pub fn sync(scratch: &Path, dir: &Path) -> Result<(), TypeScriptError> {
    let committed = entries(dir)?.unwrap_or_default();
    if let Some(name) = committed
        .iter()
        .find_map(|(name, entry)| (!is_generated(name, entry)).then_some(name))
    {
        return Err(TypeScriptError::Foreign {
            path: dir.join(name),
        });
    }
    // Every check comes before the first change: the export holds only files.
    let mut fresh = BTreeMap::new();
    for (name, entry) in entries(scratch)?.unwrap_or_default() {
        let Entry::File(contents) = entry else {
            return Err(TypeScriptError::Foreign {
                path: scratch.join(name),
            });
        };
        fresh.insert(name, contents);
    }
    std::fs::create_dir_all(dir).map_err(|source| TypeScriptError::Io {
        path: dir.to_path_buf(),
        source,
    })?;
    for name in committed.keys().filter(|name| !fresh.contains_key(*name)) {
        let path = dir.join(name);
        std::fs::remove_file(&path).map_err(|source| TypeScriptError::Io { path, source })?;
    }
    for (name, contents) in &fresh {
        let unchanged =
            matches!(committed.get(name), Some(Entry::File(current)) if current == contents);
        if !unchanged {
            let path = dir.join(name);
            std::fs::write(&path, contents)
                .map_err(|source| TypeScriptError::Io { path, source })?;
        }
    }
    Ok(())
}

/// Exports into `scratch`, then syncs `dir` with it: `just gen`.
///
/// # Errors
/// As [`export`] and [`sync`]; when the export fails, `dir` is untouched.
pub fn write(scratch: &Path, dir: &Path) -> Result<(), TypeScriptError> {
    export(scratch)?;
    sync(scratch, dir)
}

/// Exports into `scratch`, then compares `dir` with it: `just gen-check`.
///
/// # Errors
/// As [`export`] and [`compare`].
pub fn check(scratch: &Path, dir: &Path) -> Result<Vec<Difference>, TypeScriptError> {
    export(scratch)?;
    compare(scratch, dir)
}

/// An entry of a folder.
#[derive(Debug, PartialEq, Eq)]
enum Entry {
    /// A regular file and its contents.
    File(Vec<u8>),
    /// Anything else: a folder or a link.
    Other,
}

/// Whether `entry` is a file ts-rs generated: a `.ts` file that starts with
/// [`TS_RS_HEADER`].
fn is_generated(name: &OsString, entry: &Entry) -> bool {
    let is_ts = Path::new(name)
        .extension()
        .is_some_and(|extension| extension == "ts");
    matches!(entry, Entry::File(contents) if is_ts && contents.starts_with(TS_RS_HEADER.as_bytes()))
}

/// Every entry of `dir` by name; `None` if `dir` doesn't exist.
fn entries(dir: &Path) -> Result<Option<BTreeMap<OsString, Entry>>, TypeScriptError> {
    let io_error = |path: &Path| {
        let path = path.to_path_buf();
        move |source| TypeScriptError::Io { path, source }
    };
    let read_dir = match std::fs::read_dir(dir) {
        Ok(read_dir) => read_dir,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(io_error(dir)(error)),
    };
    let mut entries = BTreeMap::new();
    for entry in read_dir {
        let entry = entry.map_err(io_error(dir))?;
        let path = entry.path();
        let file_type = entry.file_type().map_err(io_error(&path))?;
        let value = if file_type.is_file() {
            Entry::File(std::fs::read(&path).map_err(io_error(&path))?)
        } else {
            Entry::Other
        };
        entries.insert(entry.file_name(), value);
    }
    Ok(Some(entries))
}

#[cfg(test)]
mod tests {
    use std::fs;

    use tempfile::TempDir;

    use super::*;

    /// A fresh folder holding `files`.
    fn folder(files: &[(&str, &str)]) -> TempDir {
        let dir = TempDir::new().unwrap();
        for (name, contents) in files {
            fs::write(dir.path().join(name), contents).unwrap();
        }
        dir
    }

    /// A file as ts-rs writes it.
    fn generated(body: &str) -> String {
        format!("{TS_RS_HEADER}{body}")
    }

    /// Every file in `dir`, by name.
    fn contents(dir: &Path) -> BTreeMap<String, String> {
        fs::read_dir(dir)
            .unwrap()
            .map(|entry| {
                let entry = entry.unwrap();
                let name = entry.file_name().into_string().unwrap();
                (name, fs::read_to_string(entry.path()).unwrap())
            })
            .collect()
    }

    fn name(name: &str) -> PathBuf {
        PathBuf::from(name)
    }

    #[test]
    fn identical_folders_have_no_differences() {
        let scratch = folder(&[("A.ts", "a"), ("B.ts", "b")]);
        let dir = folder(&[("A.ts", "a"), ("B.ts", "b")]);

        assert_eq!(compare(scratch.path(), dir.path()).unwrap(), []);
    }

    #[test]
    fn missing_extra_and_changed_files_are_named() {
        let scratch = folder(&[("Same.ts", "s"), ("New.ts", "n"), ("Edited.ts", "new")]);
        let dir = folder(&[("Same.ts", "s"), ("Old.ts", "o"), ("Edited.ts", "old")]);

        let differences = compare(scratch.path(), dir.path()).unwrap();

        assert_eq!(
            differences,
            [
                Difference::Changed(name("Edited.ts")),
                Difference::Missing(name("New.ts")),
                Difference::Extra(name("Old.ts")),
            ]
        );
        assert_eq!(differences[0].to_string(), "changed: Edited.ts");
        assert_eq!(differences[1].to_string(), "missing: New.ts");
        assert_eq!(differences[2].to_string(), "not in the export: Old.ts");
    }

    #[test]
    fn a_missing_folder_lacks_every_file() {
        let scratch = folder(&[("A.ts", "a")]);
        let parent = TempDir::new().unwrap();

        let differences = compare(scratch.path(), &parent.path().join("generated")).unwrap();

        assert_eq!(differences, [Difference::Missing(name("A.ts"))]);
    }

    #[test]
    fn a_subfolder_in_the_folder_is_a_difference() {
        let scratch = folder(&[("A.ts", "a")]);
        let dir = folder(&[("A.ts", "a")]);
        fs::create_dir(dir.path().join("nested")).unwrap();

        let differences = compare(scratch.path(), dir.path()).unwrap();

        assert_eq!(differences, [Difference::Extra(name("nested"))]);
    }

    #[test]
    fn sync_removes_stale_generated_files_and_writes_new_and_changed_ones() {
        let scratch = folder(&[
            ("Same.ts", &generated("s")),
            ("New.ts", &generated("n")),
            ("Edited.ts", &generated("new")),
        ]);
        let dir = folder(&[
            ("Same.ts", &generated("s")),
            ("Old.ts", &generated("o")),
            ("Edited.ts", &generated("old")),
        ]);

        sync(scratch.path(), dir.path()).unwrap();

        assert_eq!(contents(dir.path()), contents(scratch.path()));
    }

    #[rstest::rstest]
    #[case::hand_written("notes.md", "my notes")]
    #[case::ts_without_the_header("Mine.ts", "export type Mine = string;\n")]
    #[case::header_in_another_extension("Copy.js", TS_RS_HEADER)]
    fn sync_stops_at_a_file_ts_rs_didnt_generate_and_deletes_nothing(
        #[case] file: &str,
        #[case] text: &str,
    ) {
        let scratch = folder(&[("New.ts", &generated("n"))]);
        let dir = folder(&[("Old.ts", &generated("o")), (file, text)]);
        let before = contents(dir.path());

        let error = sync(scratch.path(), dir.path()).unwrap_err();

        assert!(
            matches!(&error, TypeScriptError::Foreign { path } if *path == dir.path().join(file)),
            "{error:?}"
        );
        assert_eq!(contents(dir.path()), before);
    }

    #[test]
    fn sync_stops_at_a_subfolder_and_deletes_nothing() {
        let scratch = folder(&[("New.ts", &generated("n"))]);
        let dir = folder(&[("Old.ts", &generated("o"))]);
        fs::create_dir(dir.path().join("nested")).unwrap();

        let error = sync(scratch.path(), dir.path()).unwrap_err();

        assert!(
            matches!(&error, TypeScriptError::Foreign { path } if *path == dir.path().join("nested")),
            "{error:?}"
        );
        assert!(dir.path().join("Old.ts").exists());
        assert!(!dir.path().join("New.ts").exists());
    }

    #[test]
    fn sync_creates_a_missing_folder() {
        let scratch = folder(&[("A.ts", &generated("a"))]);
        let parent = TempDir::new().unwrap();
        let dir = parent.path().join("generated");

        sync(scratch.path(), &dir).unwrap();

        assert_eq!(contents(&dir), contents(scratch.path()));
    }

    #[test]
    fn a_leftover_in_the_scratch_folder_never_reaches_the_folder() {
        let scratch = folder(&[("Leftover.ts", &generated("from an earlier run"))]);
        let dir = folder(&[("Old.ts", &generated("o"))]);
        let before = contents(dir.path());

        let error = write(scratch.path(), dir.path()).unwrap_err();

        assert!(
            matches!(&error, TypeScriptError::ScratchNotEmpty { path } if path == scratch.path()),
            "{error:?}"
        );
        assert_eq!(contents(dir.path()), before);
    }

    #[test]
    fn check_reports_a_stale_folder() {
        let scratch = TempDir::new().unwrap();
        let dir = folder(&[("Old.ts", &generated("o"))]);

        let differences = check(scratch.path(), dir.path()).unwrap();

        assert!(
            differences.contains(&Difference::Extra(name("Old.ts"))),
            "{differences:?}"
        );
        assert!(
            differences.contains(&Difference::Missing(name("ErrorResponse.ts"))),
            "{differences:?}"
        );
    }

    #[test]
    fn exporting_into_a_missing_scratch_folder_fails() {
        let parent = TempDir::new().unwrap();
        let scratch = parent.path().join("missing");

        let error = export(&scratch).unwrap_err();

        assert!(
            matches!(&error, TypeScriptError::Io { path, .. } if *path == scratch),
            "{error:?}"
        );
    }

    #[test]
    fn write_exports_and_syncs_the_folder() {
        let scratch = TempDir::new().unwrap();
        let dir = folder(&[("Old.ts", &generated("o"))]);

        write(scratch.path(), dir.path()).unwrap();

        assert_eq!(contents(dir.path()), contents(scratch.path()));
        assert!(dir.path().join("ErrorResponse.ts").exists());
        assert!(!dir.path().join("Old.ts").exists());
    }

    #[test]
    fn a_file_where_a_folder_should_be_is_an_io_error() {
        let scratch = folder(&[("A.ts", "a")]);
        let parent = folder(&[("generated", "not a folder")]);
        let file = parent.path().join("generated");

        let error = compare(scratch.path(), &file).unwrap_err();

        assert!(
            matches!(&error, TypeScriptError::Io { path, .. } if *path == file),
            "{error:?}"
        );
    }

    #[test]
    fn a_folder_sync_cant_create_is_an_io_error() {
        let scratch = folder(&[("A.ts", &generated("a"))]);
        let parent = folder(&[("file", "not a folder")]);
        let dir = parent.path().join("file").join("generated");

        let error = sync(scratch.path(), &dir).unwrap_err();

        assert!(
            matches!(&error, TypeScriptError::Io { path, .. } if *path == dir),
            "{error:?}"
        );
    }

    #[test]
    fn sync_stops_at_a_subfolder_in_the_scratch_folder_and_deletes_nothing() {
        let scratch = folder(&[("New.ts", &generated("n"))]);
        fs::create_dir(scratch.path().join("nested")).unwrap();
        let dir = folder(&[("Old.ts", &generated("o"))]);
        let before = contents(dir.path());

        let error = sync(scratch.path(), dir.path()).unwrap_err();

        assert!(
            matches!(&error, TypeScriptError::Foreign { path } if *path == scratch.path().join("nested")),
            "{error:?}"
        );
        assert_eq!(contents(dir.path()), before);
    }
}
